[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
freedesktop-desktop-entry = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.115"
